### PR TITLE
Fix Context methods with stdsqlRunner

### LINKED ISSUE #162: Runner and stdsql does not contain ExecContext and QueryContext methods
After update I've got error "DB does not support Context" on next code:
```go
package main

import (
	"context"
	"database/sql"
	"log"

	"github.com/Masterminds/squirrel"
	_ "github.com/lib/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgres://postgres:postgres@localhost:5432")
	if err != nil {
		log.Fatal(err)
	}
	_, err = squirrel.Select("1").RunWith(db).QueryContext(context.Background())
	if err != nil {
		log.Fatal(err)
	}
}
```
Because on call `RunWith(db)` `*sql.DB` converting to `stdsql` interface, that has no method `QueryContext`.

### PR DESCRIPTION
**Pull request by lann**
QueryContext and ExecContext were omitted from the interface, breaking some existing code.

Fixes #162

### CODE REVIEW

File: squirrel.go [hunk 1]
```diff
@@ -63,9 +63,11 @@ type Runner interface {
 
 type stdsql interface {
 	Query(string, ...interface{}) (*sql.Rows, error)
+	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
 	QueryRow(string, ...interface{}) *sql.Row
-	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
```
Comment (james-lawrence) [inline squirrel.go]: @lann did we really mean `QuetdsqlRryRowContext` lol
